import type { Report } from "@/lib/autoixpert/types";

/**
 * Beispieldaten fuer den Demomodus (kein API-Schluessel gesetzt).
 * Bewusst frei erfunden: echte Anspruchsteller, Kennzeichen oder VIN gehoeren
 * nicht in ein Repository. Aufbau und Aktenzeichenformat (MMJJ/NNNNKK) folgen
 * eurer Praxis.
 */
export const demoReports: Report[] = [
  {
    id: "demo-2081",
    external_id: "0926/2081TG",
    token: "0926/2081TG",
    type: "liability",
    state: "recorded",
    order_date: "2026-09-06",
    created_at: "2026-09-06T08:12:00Z",
    updated_at: "2026-09-07T10:44:00Z",
    claimant: {
      salutation: "Herr",
      first_name: "Martin",
      last_name: "Beispiel",
      street_and_housenumber_or_lockbox: "An der Fuhr 3",
      zip: "50997",
      city: "Köln",
      phone: "0221 1234567",
      email: "m.beispiel@example.org",
      is_owner: true,
      represented_by_lawyer: true,
    },
    lawyer: { organization_name: "Rechtsanwalt Musterkanzlei", city: "Köln" },
    insurance: {
      organization_name: "Beispiel Versicherungs-AG",
      city: "Berlin",
      zip: "10900",
      claim_number: "AZ6U3JH",
    },
    garage: { organization_name: "Beispiel Autohaus Köln", city: "Köln", zip: "50823" },
    car: {
      license_plate: "K-MB 3119",
      vin: "WDD0000000A000000",
      make: "Mercedes-Benz",
      model: "E-Klasse Limousine",
      shape: "sedan",
      performance_kw: 320,
      performance_hp: 435,
      first_registration_date: "2018-10-12",
      latest_registration_date: "2024-10-18",
      mileage_meter: 122000,
      mileage_unit: "km",
      damage_description: "Frontverkleidung und Kotflügel rechts deformiert, Felge zerkratzt.",
      unrepaired_previous_damage: "Heckklappe deformiert, Seitenwand hinten links.",
    },
    accident: {
      date: "2026-09-06",
      location: "Otto-Hahn-Straße 6, 50997 Köln",
      police_recorded: true,
      police_department: "PP Köln",
      circumstances: "Auffahrunfall an einer Ampel.",
    },
    visits: [
      {
        id: "v1",
        street: "Jakob-Koch-Str. 1",
        zip: "41466",
        city: "Neuss",
        date: "2026-09-06",
        conditions: "ausreichend",
      },
    ],
    labels: [{ name: "Kalkuliert", color: "#ab47bc" }],
  },
  {
    id: "demo-2084",
    external_id: "0926/2084TG",
    token: "0926/2084TG",
    type: "liability",
    state: "recorded",
    order_date: "2026-09-01",
    created_at: "2026-09-01T07:30:00Z",
    updated_at: "2026-09-05T15:02:00Z",
    claimant: { salutation: "Frau", first_name: "Sabine", last_name: "Beispiel", city: "Aurich" },
    car: { license_plate: "AUR-AZ 695" },
    accident: { date: "2026-08-30" },
    labels: [{ name: "Vertrag an Kunde geschickt", color: "#4caf50" }],
  },
  {
    id: "demo-2078",
    external_id: "0926/2078TG",
    token: "0926/2078TG",
    type: "valuation",
    state: "locked",
    order_date: "2026-08-28",
    created_at: "2026-08-28T09:00:00Z",
    updated_at: "2026-09-02T11:20:00Z",
    completion_date: "2026-09-02",
    claimant: { organization_name: "Beispiel Car Handel GmbH", city: "Köln" },
    car: { license_plate: "K-BC 900", make: "Mercedes-Benz", model: "G-Klasse" },
    labels: [{ name: "Kalkuliert", color: "#ab47bc" }],
  },
  {
    id: "demo-2069",
    external_id: "0826/2069TG",
    token: "0826/2069TG",
    type: "liability",
    state: "recorded",
    order_date: "2026-08-24",
    created_at: "2026-08-24T06:45:00Z",
    updated_at: "2026-09-01T08:10:00Z",
    claimant: { salutation: "Herr", first_name: "Kai", last_name: "Beispiel", city: "Neuss" },
    car: { license_plate: "NE-RO 54", make: "Triumph", model: "Daytona" },
    accident: { date: "2026-08-22" },
    labels: [
      { name: "Vertrag an Kunde geschickt", color: "#4caf50" },
      { name: "An Rechtsanwalt versendet", color: "#ffa726" },
    ],
  },
];
